version: "3"
services:
  web:
    image: teasdalep/echo-headers-service:v4
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8001:8001"
    environment:
      - SERVICE_PORTS=8001
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    environment:
      - SERVICE_PORTS=8080
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/docker/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
  proxy:
    image: dockercloud/haproxy
    # depends_on ignored in stack swarm mode version 3 Compose file
    depends_on:
      - redis
      - web
      - visualizer
    environment:
      # default is roundrobin
      - BALANCE=leastconn
#      - HEALTH_CHECK=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  webnet:
